modkey = "Mod4"
mousekey = "Mod4"
layouts = [
    "MainAndHorizontalStack",
    "Monocle",
]
tags = ["Main", "Background", "Extra"]
disable_current_tag_swap = true

# Execute Apps
[[keybind]]
command = "Execute"
value = "alacritty -e fish"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "emacsclient -c -a emacs"
modifier = ["modkey", "Shift"]
key = "e"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey", "Shift"]
key = "d"
